add a test for ios native to capture nav bar
applitools/sdk.coverage.tests pull request #144
Opened 2022-04-07 21:58 UTC by SophieDePaula

This test was created due to [this PR](https://github.com/applitools/eyes.sdk.javascript1/pull/848)

2022-04-07 22:01 UTC, Yarden-Ingber commented on java/overrides.js
> +    'appium iOS nav bar check regio': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9214167)
```suggestion
    "appium iOS nav bar check regio": {skipEmit: true},
```

2022-04-07 22:01 UTC, Yarden-Ingber commented on python/overrides.js
> +    'appium iOS nav bar check regio': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9214167)
```suggestion
    "appium iOS nav bar check regio": {skipEmit: true},
```

2022-04-07 22:01 UTC, Yarden-Ingber commented on ruby/overrides.js
> +    'appium iOS nav bar check regio': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9214167)
```suggestion
    "appium iOS nav bar check regio": {skipEmit: true},
```

2022-04-08 13:10 UTC, tourdedave requested changes
Looks good other than the tweaks I mentioned.

If you haven't already, you'll also want to run the test and accept the new baseline in Eyes on the `Eyes SDK` team.

2022-04-08 13:10 UTC, tourdedave commented on coverage-tests.js
> +  config: {baselineName: 'Appium_iOS_CheckRegion'},
`baselineName` shouldn't be needed. It's constructed from the test name dynamically.

2022-04-08 13:10 UTC, tourdedave commented on coverage-tests.js
> +    eyes.open({appName: 'Applitools Eyes SDK', testName: 'Appium_iOS_Nav_CheckRegion'})
We shouldn't need to pass the `testName` explicitly here

2022-04-08 16:24 UTC, SophieDePaula commented
Thanks @tourdedave

2022-04-08 16:25 UTC, merged