added dom pseudo element test
applitools/sdk.coverage.tests pull request #158
Opened 2022-05-30 07:44 UTC by chaim-aharonson-applitools

2022-05-30 07:47 UTC, Yarden-Ingber commented on DotNet/overrides.js
> +    'should get dom pseudo elements when check window': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9515763)
```suggestion
    "should get dom pseudo elements when check window": {skipEmit: true},
```

2022-05-30 07:47 UTC, Yarden-Ingber commented on python/overrides.js
> +    'should get dom pseudo elements when check window': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9515763)
```suggestion
    "should get dom pseudo elements when check window": {skipEmit: true},
```

2022-05-30 07:47 UTC, Yarden-Ingber commented on java/overrides.js
> +    'should get dom pseudo elements when check window': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9515763)
```suggestion
    "should get dom pseudo elements when check window": {skipEmit: true},
```

2022-05-30 07:47 UTC, Yarden-Ingber commented on ruby/overrides.js
> +    'should get dom pseudo elements when check window': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9515763)
```suggestion
    "should get dom pseudo elements when check window": {skipEmit: true},
```

2022-05-30 07:47 UTC, Yarden-Ingber commented on python/overrides.js
> +    'Should return exception in TestResultsSummary': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9515763)
```suggestion
    "Should return exception in TestResultsSummary": {skipEmit: true},
```

2022-05-30 07:48 UTC, Yarden-Ingber commented on ruby/overrides.js
> +    'Should return exception in TestResultsSummary': {skipEmit: true},
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/applitools/sdk.coverage.tests/pullRequest?prid=9515763)
```suggestion
    "Should return exception in TestResultsSummary": {skipEmit: true},
```

2022-06-01 12:48 UTC, amitzur requested changes
I believe this is unnecessary.

2022-06-01 12:48 UTC, amitzur commented on coverage-tests.js
> +test('should get dom pseudo elements when check window', {
Honestly, I don't think we need a generic coverage test for this fix. Only a test in `dom-capture`. I can explain this to anyone if needed.

2022-06-02 08:05 UTC, chaim-aharonson-applitools commented on coverage-tests.js
> +test('should get dom pseudo elements when check window', {
test was removed (actually the whole PR)

2022-06-02 08:06 UTC, closed without merging